language: bash
sudo: false
cache: apt

before_script:
  - wget https://software-lab.de/picoLisp-18.12.tgz -O /tmp/picolisp.tgz
  - cd /tmp; tar -xf /tmp/picolisp.tgz
  - cd /tmp/picoLisp; wget https://software-lab.de/x86-64.linux.tgz
  - tar -xf x86-64.linux.tgz
  - cd /tmp/picoLisp/src64 && make
  - export PATH=$PATH:/tmp/picoLisp
  - make clean; make

script:
  - export PATH=$PATH:/tmp/picoLisp
  - cd ${TRAVIS_BUILD_DIR} && make check
