[de MODULE_INFO
  ("name"       "picolisp-semver")
  ("version"    "0.10.0")
  ("summary"    "PicoLisp SemVer")
  ("source"     "https://jidoteki.com")
  ("author"     "Alexander Williams")
  ("license"    "MIT")
  ("copyright"  "(c) 2017-2018 Alexander Williams, Unscramble <license@unscramble.jp>")
  ("install"    "make")
  ("requires"
    ("picolisp-unit"    "v2.1.0"    "https://github.com/aw/picolisp-unit.git") ]
